/// Flutter icons RaiderIO
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.

import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontPkg = null;

  static const IconData raiderio = IconData(0xe800, fontFamily: 'RaiderIO', fontPackage: _kFontPkg);
  static const IconData wowup_512 = IconData(0xe800, fontFamily: 'WowUp', fontPackage: _kFontPkg);
}
